name = "Project 404"
author = "Irgendwer"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5def03827c1feb1184d1fd38a15d76b383349b7e047ea348d623c637d034a6fe"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
